// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: ../wire-runtime/src/test/proto/oneof_primitives.proto
package com.squareup.wire.protos.one_of;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.STRING;

public final class OneOfPrimitives extends Message {

  public static final String DEFAULT_DUMMY = "";

  @ProtoField(tag = 1, type = STRING)
  public final String dummy;

  public OneOfPrimitives(String dummy) {
    this.dummy = dummy;
  }

  private OneOfPrimitives(Builder builder) {
    this(builder.dummy);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof OneOfPrimitives)) return false;
    return equals(dummy, ((OneOfPrimitives) other).dummy);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    return result != 0 ? result : (hashCode = dummy != null ? dummy.hashCode() : 0);
  }

  public static final class Builder extends Message.Builder<OneOfPrimitives> {

    public String dummy;

    public Builder() {
    }

    public Builder(OneOfPrimitives message) {
      super(message);
      if (message == null) return;
      this.dummy = message.dummy;
    }

    public Builder dummy(String dummy) {
      this.dummy = dummy;
      return this;
    }

    @Override
    public OneOfPrimitives build() {
      return new OneOfPrimitives(this);
    }
  }
}
